version: "3.7"
services:
  api:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    build: .
    image: headsrooms/historedge
    ports:
      - 80:80
    command: /usr/local/poetry/bin/poetry run uvicorn historedge_backend.api.app:app --reload --workers $API_WORKERS --port 80 --host 0.0.0.0
  realtime_logger:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - api
      - db
    env_file:
      - .env
    image: headsrooms/historedge
    command: /usr/local/poetry/bin/poetry run python -m historedge_backend.realtime_logger.service
  history_distributor:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - api
      - db
    env_file:
      - .env
    image: headsrooms/historedge
    command: /usr/local/poetry/bin/poetry run python -m historedge_backend.history_distributor.service
  history_logger:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - api
      - db
    env_file:
      - .env
    image: headsrooms/historedge
    command: /usr/local/poetry/bin/poetry run python -m historedge_backend.history_logger.service
  scraper_distributor:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    image: headsrooms/historedge
    command: /usr/local/poetry/bin/poetry run python -m historedge_backend.scraper_distributor.service
  scraper:
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
      - scraper_distributor
    env_file:
      - .env
    image: headsrooms/historedge
    command: /usr/local/poetry/bin/poetry run python -m historedge_backend.scraper.service
  redis:
    image: redis:latest
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
