apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loki-grafana
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        backend:
          serviceName: loki-grafana
          servicePort: 3000