apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/service.sticky: "true"
spec:
  selector:
    app: api
  ports:
  - port: 80
    name: http
    targetPort: 80